apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: gestion-production
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: gcr.io/jeeapplication-494610/backend:latest
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"
            - name: DB_URL
              value: "jdbc:mysql://mysql:3306/gestion_production?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true"
            - name: DB_USERNAME
              value: "root"
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: mysql-root-password
            - name: CORS_ALLOWED_ORIGINS
              value: "http://104.199.58.8,http://frontend:4000"
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: gestion-production
spec:
  selector:
    app: backend
  ports:
    - port: 8080
      targetPort: 8080
