# --- DATABASE CONFIGURATION ---
# "mysql-service" doit correspondre au nom du service défini dans ton mysql-deployment.yml
spring.datasource.url=jdbc:mysql://mysql-service:3306/gestion_production?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false
spring.datasource.username=root
# Utilise le mot de passe que tu as défini dans ton secrets.yml (probablement 'rootpassword')
spring.datasource.password=rootpassword
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# --- JPA / HIBERNATE ---
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


# On expose les métriques pour Prometheus
management.endpoints.web.exposure.include=health,info,prometheus
management.endpoint.prometheus.enabled=true
management.metrics.export.prometheus.enabled=true

# --- SWAGGER & SERVER ---
springdoc.swagger-ui.path=/swagger-ui.html
server.port=8080